### ISSUE TITLE
I cant build to production

### ISSUE THREAD

**Issue by JuanCamilo0809** [BukhariMuslim/react-native-printer#1]
> Task :react-native-printer:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-printer:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.

**Comment by Hermanyo** [comment]
Did u want it yet?
If yes, try to add on your `/android/build.gradle` add below code in the end of line:

Try with u  compileSdkVesion/buildToolsVersion
```javascript 
subprojects {  // <-- Add this line
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        }
    }
}```

**Comment by JuanCamilo0809** [comment]
> Did u want it yet?
> If yes, try to add on your `/android/build.gradle` add below code in the end of line:
> 
> Try with u compileSdkVesion/buildToolsVersion
> 
> ```js
> subprojects {  // <-- Add this line
>     afterEvaluate {project ->
>         if (project.hasProperty("android")) {
>             android {
>                 compileSdkVersion 28
>                 buildToolsVersion '28.0.3'
>             }
>         }
>     }
> }```
> ```

pefect!!
